### PR TITLE
BUG: DistinguishersToColors now matches to hematoxylin and eosin

### LINKED ISSUE #22: Hematoxylin and Eosin are getting mixed up; failed
Traceback (most recent call last):
  File "/home/rainco/Yuhan/Models/Data_Process/Local_Data_Process/201201_color_norm_test.py", line 18, in <module>
    color_index_suppressed_by_eosin=1)
  File "/home/rainco/anaconda3/envs/py36_env/lib/python3.6/site-packages/itkHelpers.py", line 118, in image_filter_wrapper
    return image_filter(*args, **kwargs)
  File "/home/rainco/anaconda3/envs/py36_env/lib/python3.6/site-packages/itk/itkStructurePreservingColorNormalizationFilterPython.py", line 1180, in structure_preserving_color_normalization_filter
    return instance.__internal_call__()
  File "/home/rainco/anaconda3/envs/py36_env/lib/python3.6/site-packages/itk/ITKCommonBasePython.py", line 1585, in __internal_call__
    self.UpdateLargestPossibleRegion()
RuntimeError: ../../../include/itkStructurePreservingColorNormalizationFilter.hxx:193:
itk::ERROR: Hematoxylin and Eosin are getting mixed up; failed

Process finished with exit code 1

### LINKED ISSUE #23: not working for some H&E images
I attached a sample image on which it is not working and through following error.
RuntimeError: D:\a\im\include\itkStructurePreservingColorNormalizationFilter.hxx:156:
itk::ERROR: The image to be normalized could not be processed; does it have white, blue, and pink pixels?
img_Adrenal_gland_3_01134

### PR DESCRIPTION
**Pull request by Leengit**
A bug report indicated an exception thrown for `Hematoxylin and Eosin are getting mixed up; failed` when it should not have.  Further investigation indicated that an earlier exception should have been thrown for `The image to be normalized could not be processed; does it have white, blue, and pink pixels?`.  That was triggered because the same distinguisher was best at suppressing both the color suppressed by hematoxylin and the color suppressed by eosin.  The proper behavior is that the distinguishers assigned to these stains should be distinct.

The fix has a new approach for matching distinguishers with stains.  Specifically, when considering only the 2-dimensional plane that is the colors that are suppressed by hematoxylin and eosin, the angle of each distinguisher suppression vector can be measured in that plane.  The assignment of distinguisher to stain is based upon which distinguisher is closer in angle to that stain's axis.

### CODE REVIEW

File: include/itkStructurePreservingColorNormalizationFilter.h [hunk 1]
```diff
@@ -131,6 +131,9 @@ class StructurePreservingColorNormalizationFilter : public ImageToImageFilter<TI
   static constexpr SizeValueType maxNumberOfIterations{ 0 };
   /** Select a subset of the pixels if the image has more than this */
```
Comment (dzenanz) [inline include/itkStructurePreservingColorNormalizationFilter.h:132]: The PR description might be useful as a commit message too.

**Review by dzenanz — APPROVED** [review]
Code looks good.

File: include/itkStructurePreservingColorNormalizationFilter.h (hunk 1 above)
Comment (Leengit) [reply include/itkStructurePreservingColorNormalizationFilter.h:132]: I just pushed an extended commit message.

**Review by dzenanz — APPROVED** [review]
